url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Justin's Blog" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-paginate-v2

permalink: /:year/:month/:day/:title


autopages:
  enabled: true
  tags: 
    enabled: false
  categories:
    layouts:
      - category_index.html
    enabled: true
  collections:
    enabled: false
    slugify:
      mode: 'ascii'
      cased: true  # Causes B+W tag to show up as it is written on the terry-pratchet-diary-2017.md page and not lowercase
    
# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  offset: 2
  permalink: '/page:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

  

############################################################
# Old jekyll-paginate pagination logic
#   Uncomment thew two entries below to demonstrate how this new gem
#   retains backwards compatibility with the old pagination logic 
#   AS OF JANUARY 2018 this code does not work anymore!
#paginate: 3
#paginate_path: "/legacy/page:num/"


